New azure_rag pipeline
Synapxe-DNA/healthhub-content-optimization pull request #161
Opened 2024-08-28 02:39 UTC by richmondsin

This is the new pipeline for data processing for the azure indexing.

2024-08-28 02:41 UTC, Wilsven commented
Hi, could you please elaborate on your PR? It is best practice, as mentioned before.

2024-08-28 02:42 UTC, Wilsven commented
> Hi, could you please elaborate on your PR? It is best practice, as mentioned before.

Your branch is also not up-to-date with the main branch. Have you pulled in the latest changes to your branch before making a PR?

2024-08-28 02:45 UTC, Wilsven requested changes
- Update in detail changes in this PR
- Branch should be up-to-date

2024-08-28 02:57 UTC, Wilsven requested changes

2024-08-28 02:57 UTC, Wilsven commented on content-optimization/requirements.txt
> +azure-cli
Can you specify the version?

2024-08-28 02:57 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        azure_endpoint="https://cog-zicuh2lqrbb2s.openai.azure.com",
This endpoint should not be committed to version control. Please read up on how to deal with credentials using Kedro.

2024-08-28 02:57 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/azure_rag/nodes.py
> +        ~filtered_data_rag["id"].isin([1445629, 1443608, 1435183, 1435335, 1434652])
Please do not hardcode. Use the configuration file.

2024-08-28 05:55 UTC, richmondsin commented on content-optimization/src/content_optimization/pipelines/azure_rag/nodes.py
> +        ~filtered_data_rag["id"].isin([1445629, 1443608, 1435183, 1435335, 1434652])
Done.

2024-08-28 05:55 UTC, richmondsin commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        azure_endpoint="https://cog-zicuh2lqrbb2s.openai.azure.com",
Done.

2024-08-28 05:55 UTC, richmondsin commented on content-optimization/requirements.txt
> +azure-cli
Done.

2024-08-28 05:55 UTC, richmondsin commented
> Hi, could you please elaborate on your PR? It is best practice, as mentioned before.

2024-08-28 06:03 UTC, Wilsven requested changes

2024-08-28 06:03 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        model="chat",
Can you put the deployment name in the configuration file or credential file as well? Either one will do.

2024-08-28 06:03 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        max_tokens=2000,
All these parameters can go into the configuration file. You never know when we might want to tweak these.

2024-08-28 06:15 UTC, richmondsin commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        model="chat",
Done.

2024-08-28 06:16 UTC, richmondsin commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        max_tokens=2000,
But when they tweak this, they will look into this script. And this is a separate python file that I import into the nodes.py so the parameters.yml is not tied to this.

2024-08-28 06:20 UTC, Wilsven commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        max_tokens=2000,
You are making the assumption they do refer to your script. Your script in this pipeline shouldn't be looked at when we are running iterations on the pipeline. If we want to run it with different parameters, it should be as simple as configuring your configuration file. 

I do not get your point on 

> And this is a separate python file that I import into the nodes.py so the parameters.yml is not tied to this.

I do not get your point on this. Even if it is imported from a `utils.py`, these are just functions where arguments to one function can be the arguments of another function. Your node function can simply take as parameters these arguments.

2024-08-28 06:22 UTC, Wilsven requested changes
Resolve remaining comments.

2024-08-28 06:53 UTC, richmondsin commented on content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
> +        max_tokens=2000,
Done.

2024-08-28 07:14 UTC, merged

2024-09-05 03:22 UTC, Wilsven commented
@richmondsin Could you please update the `README.md` in the [File Structure section](https://github.com/Synapxe-DNA/healthhub-content-optimization/tree/main?tab=readme-ov-file#file-structure) as to what the data you committed under the `01_raw` is?